### ISSUE TITLE
Fixed width columns

### ISSUE THREAD

**Issue by geleto** [peterramsing/lost#142]
Sometimes I need fixed width columns - for instance menu sidebars rarely need resizable columns.
For this to work Lost needs to be aware of the fixed-size columns inside a container and distribute the remaining space among the fractional columns. This can be done by assigning the columns to the same group:

``` css
.sidebar {
    lost-column: 18rem;
    lost-group: "main";
}
.column-one{
    lost-column: 1/2;
    lost-group: "main";
}
.column-two{
    lost-column: 1/2;
    lost-group: "main";
}
```

... and to remove some duplication - the above sample can be written like this:

``` css
.sidebar {
    lost-column: 18rem;
    lost-group: "main";
}
.column{
    lost-column: 1/2;
    lost-group: "main" 2;
}
```

Obviously the same should work for rows too.
This can also help to automatically detect the last item when applying cycle.
