### ISSUE TITLE
Is there a tutorial for lost stylus?

### ISSUE THREAD

**Issue by rlam3** [peterramsing/lost#186]
Is there a tutorial for lost stylus?

**Comment by peterramsing** [comment]
Does this help? 
https://youtu.be/xTcOUh4rKMo

**Comment by peterramsing** [comment]
@rlam3 Can this issue be closed? :smiley:

**Comment by lewk07** [comment]
This https://github.com/peterramsing/lost/tree/gh-pages is actually written in stylus. Which is kind of weird considering the rest of the docs seem pretty standard. If you're asking because you're running into issues, or things just seem to not be working. I'm using stylus and having plenty of issues. Things just don't work. I don't know if it's stylus, postcss, postcss via the stylus plugin. Stuff is just weird, and I'm not skilled enough to articulate why.

**Comment by peterramsing** [comment]
We migrated away from Stylus where I work as there were a lot of issues in compiling.

In theory, if Stylus is compiling properly then Lost will work just fine. If there are specific issues I'd love to hear about them so we can see if it's Lost causing them.

**Comment by corysimmons** [comment]
Your processing should go Stylus -> CSS -> Lost -> CSS.

So something like:

``` stylus
.foo
  background: darken(red, 20%)
  lost-column: 1/2
```

gets turned into:

``` css
.foo {
  background: #f50000;
  lost-column: 1/2; /* stylus ignores this line since it doesn't recognize the rule */
}
```

then Lost runs over it and sees the `lost-column` rule and turns that CSS into the finished product CSS:

``` css
.foo {
  background: #f50000;
  width: calc(99.99% * 1/2 - (30px - 30px * 1/2));
}
.foo:nth-child(n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
.foo:last-child {
  margin-right: 0;
}
.foo:nth-child(2n) {
  margin-right: 0;
}
.foo:nth-child(2n + 1) {
  clear: left;
}
```

Notice how Stylus' changes (the `darken(red, 20%)` color hasn't been touched but Lost has produced a plethora of CSS rules where `lost-column` was.

But yeah, the `gh-pages` branch is a perfect example of Lost working fine with a preprocessor: https://github.com/peterramsing/lost/blob/gh-pages/src/css/style.styl#L40

Let us know if you can articulate your problem or have some example code. Preferably in a new issue.
