### ISSUE TITLE
I need help with my grid

### ISSUE THREAD

**Issue by qrczak** [peterramsing/lost#199]
My html

``` html
div.row
  div.item
  div.long
  div.item
  div.long
  div.item
  div.long
```

where

``` css
div.row {
  lost-utility: clearfix;
}

div.item {
  lost-column: 2/5;
}

div.long {
  lost-column: 3/5;
}
```

and how to make this divs like this

```
[   div.item   ] [         div.long         ]
[   div.item   ] [         div.long         ]
[   div.item   ] [         div.long         ]
[   div.item   ] [         div.long         ]
```

because right now there is a little mess:

![My mess](http://i.imgur.com/JWy4N0X.png)

I was trying with cycles but with no resoults...

Can anybody help me?

**Comment by peterramsing** [comment]
The main issue here is that because you specified `x/5`, you are cycling every 5th div.

You were on the right path but I think you may have missed some syntax. I'm hoping to get some more documentation on this soon.

**Try this out for your css.**

``` css
div.row {
  lost-utility: clearfix;
}

div.item {
  lost-column: 2/5 2;
}

div.long {
  lost-column: 3/5 2;
}
```

*note the `2` on the end of those `lost-column` declarations. That does the clearing to get you the results you want.

![screen shot 2015-12-28 at 10 42 34 pm](https://cloud.githubusercontent.com/assets/3523268/12030494/519c37fa-adb4-11e5-8cc7-690e4a7f3f97.png)
