### ISSUE TITLE
Right align grid elem

### ISSUE THREAD

**Issue by pixelize** [peterramsing/lost#201]
Hi everyone,

It might be stupid but I'd like to align the last 3 items to the right. (the button is not in the grid and positioned by an absolute position).
I tried some align helpers but can't figure it out ;)

Thanks in advance

![capture d ecran 2015-12-23 a 12 43 11](https://cloud.githubusercontent.com/assets/2931627/11975903/c38366d6-a972-11e5-996e-7e5504c930da.png)

**Comment by peterramsing** [comment]
Could you elaborate a bit more? Maybe share some code?

Is the attached image what you have right now? Could you show what you want it to look like with some annotations?

**Comment by corysimmons** [comment]
Lost works best when you mix and match it with other layout methods and techniques instead of trying to bend Lost to be an all-in-one layout tool.

For instance: http://codepen.io/corysimmons/pen/NxbbgO?editors=110

That said, @pixelize brings up an interesting point. Should `lost-align` work on single elements as well? Perhaps an arg that specifies something is a single element.

Right now there is no way to do this, but it might be cool to simply write some code like:

``` css
.block {
  position: relative;
}

.left {
  lost-align: left single;
}

.mid {
  lost-align: center single;
}

.right {
  lost-align: right single;
}
```

Or something like that?
