### ISSUE TITLE
Last column resolves too wide using lost-column: 6/12 0

### ISSUE THREAD

**Issue by MartinDM** [peterramsing/lost#204]
Having issue setting this to work. Even with two equally wide columns, using lost-column: 6/12 0 renders the second column too wide and it pops onto a second line. Trying a different propoertion shows the same issue:

``` scss
row {
    lost-utility: clearfix;
        .story {
        lost-column: 8/12 0;
    }
    .story__secondary {
        lost-column: 4/12 0;
    }
}
```

Works when using a fraction, or totalling 11.
What could it be?

Cheers
