### ISSUE TITLE
Support for static columns?

### ISSUE THREAD

**Issue by jrmyio** [peterramsing/lost#240]
I am comparing susy and lost to find out which has the most support for edge cases. Is it true that lost doesn't support any sort static/hybrid approach?

Let's say I want to stack four columns as following:

50px  |   1/3rd(-50px)   |   1/3rd(-50px)  |   1/3rd(-50px)

Is there any way to do this with lost?

**Comment by peterramsing** [comment]
Currently, there isn't a way to do this natively, no. Double check me on this @corysimmons. The way that I have done this is to separate out the fixed column outside of a container. Here's what I do for this:

``` html
<body>

  <div class="one">
  </div>

  <div class="container">
    <div class="two">
    </div>
    <div class="three">
    </div>
    <div class="four">
    </div>
  </div>

</body>
```

``` css
.container {
  float: left;
  width: calc(100% - (50px + 30px));
}

.one,
.two,
.three,
.four {
  height: 300px;
}

.one {
  width: 50px;
  float: left;
  margin-right: 30px;
}

.two,
.three,
.four {
  lost-column: 1/3;
  lost-column-cycle: 4;
}
```
