### ISSUE TITLE
lost-align leads grid to collapse

### ISSUE THREAD

**Issue by txixx** [peterramsing/lost#267]
Hi!
my page markup is looking like this:

``` html
<main class="wrap">
    <div class="grid-one">
```

And as .grid-item:

``` html
    <div class="grid-item>"
        <a href="#">
            <img src="path-to-img">
            <div>
                <h3>Heading</h3>
            </div>
        </a>
    </div>
```

My css:

``` scss
header, main, .wrap {
    lost-center: 60rem;
    padding: 0 0.25rem;
    width: 100%;
}
```

and

``` scss
.grid-one {

    & .grid-item {
        lost-column: 1/3;
        lost-align: center;
        height: 100%;

        & a {
            height: 6rem;
        }

        & img {
            display: block;
        }

        & div {
            lost-align: middle-center;
            lost-column: 1/1;
            height: inherit;

            & h3 {
                text-align: center;
                z-index: 2;
            }

        }
    }
}
```

What I'm trying to achieve is the `<h3>` to center vertically and horizontally above the `<img>`.
What it does is collapsing the hole grid into two small columns and everything is overlapping!

![lost-collapsed](https://cloud.githubusercontent.com/assets/15063582/13586575/10f820c0-e4c2-11e5-9160-a623359c4d20.JPG)

Deleting `lost-align: center` from `.grid-item` will make the grid look correctly, but wont lead to the `<h3>` show as wanted...

Is this normal behaviour? Are there too many objects nested (or wrong nested?)

Thank you,
