### ISSUE TITLE
[SOLVED] lost-column: 1/24 is too small

### ISSUE THREAD

**Issue by dotnetCarpenter** [peterramsing/lost#282]
Actually, after writing this issue it dawned on me. The 1/24 is not too small but my gutter is too big to make sense in such a small context. I'll leave this in case others run into a similar issue with very fined grained grids with a big gutter.

I've made a simple grid with [lost](https://github.com/peterramsing/lost/) and is testing it right now. [lost](https://github.com/peterramsing/lost/) seem to work flawlessly except for one case. When I have column that is 1/24 wide.

http://codepen.io/dotnetCarpenter/pen/eZQOVL?editors=1100

``` css
.f-row_24 .f-row__cell_1 {
    lost-column: 1/24 flex;
}
```

I also tried without flexbox (e.g. float), just using `lost-column: 1/24` and remove the other flex properties with the exact same visual output.

The CSS output ion the flex instance is:

``` css
.f-row_24 .f-row__cell_1 {
    flex: 0 0 auto;
    width: calc(99.99% * 1/24 - (3.6rem - 3.6rem * 1/24));
}
```
