### ISSUE TITLE
Lost-column not always working

### ISSUE THREAD

**Issue by AljanScholtens** [peterramsing/lost#287]
Hi,

In my boilerplate I'm using Lost, but I have some trouble with it, because in some situations it works perfectly and in others not. And I have no clue what I can do about it. Can anyone tell me what I'm doing wrong here? An example in the codepen below. Thanks!

http://codepen.io/aljan/pen/vGPbgr?editors=1100

**Comment by peterramsing** [comment]
Hey @AljanScholtens 

There are several ways to make this work.
1st. Update the HTML to allow the `:last-child` rule to work.

``` html
<div class="l-grid">
  <div class="l-3">l-3</div>
  <div class="l-9">l-9</div>
</div>
<!-- Closing and Opening the div -->
<div class="l-grid">
  <div class="l-6">l-6</div>
  <div class="l-6">l-6</div>
</div>
```

2nd. This comes into a larger thought process on how to use LostGrid. You're using LostGrid similar to how one might use Bootstrap. You're putting the grid in the `html`. There is nothing wrong with that but LostGrid is more designed with Semantic CSS in mind. (Here's a quick post I found: [What Makes For a Semantic Class Name?](https://css-tricks.com/semantic-class-names/) )
It is hard to do Semantic while making a grid within your `html`. It would prescribe `html` that looks more like this:

``` html
<div class="page-intro">
  <div class="author-bio">I like cheese!</div>
  <div class="author-cool-picture">:)</div>

  <div class="fatty-cheeses">Delish</div>
  <div class="creamy-cheeses">Mmmmm</div>
</div>
```

``` css
.page-intro {
  lost-utility: clearfix;
}

.author-bio {
  lost-column: 3/12;
  outline: 1px solid red;
  margin-bottom: 2.08333%;
  padding: 0.5rem;
  text-align: center;
}

.author-cool-picture {
  lost-column: 9/12 2;
  outline: 1px solid red;
  margin-bottom: 2.08333%;
  padding: 0.5rem;
  text-align: center;
}

.fatty-cheeses,
.creamy-cheeses {
  lost-column: 6/12 2;
  outline: 1px solid red;
  margin-bottom: 2.08333%;
  padding: 0.5rem;
  text-align: center;
}
```

Now I understand that the 2nd option is not a framework per se. This is what is right for the project. Some projects are needing a framework and others are wanting to separate the visuals from the html. This being said, LostGrid might not be what you're looking for. _I love that you're using it_ _and_ I really want you to find the best tool for the job. Let me know if this helps and please feel free to reach out!

**Comment by AljanScholtens** [comment]
Thanks a lot Peter! It works and I think I made a beginners mistake.. :-P
I don't work often with these classes like .l-6, but I need them in a large web application. And you're absolutely right about semantics. But I also prefer display patterns over content patterns (http://danielmall.com/articles/content-display-patterns/).

**Comment by peterramsing** [comment]
@AljanScholtens There are so many ways to do all of this...it's what makes being a FED such a challenging job these days.

My current day job has me working on a lot of one-off pages that are not intended to be re-used so my example used classes like the ones that I did. LostGrid is also going to be great for the example in the [article](http://danielmall.com/articles/content-display-patterns/) (great share by the way!).

``` html
<div class="event">
    <h1 class="event__title">Star Wars: The Force Awakens Premiere</h1>
    <p class="event__date">Dec 20, 2015</p>
    <p class="event__location">Ritz East, Philadelphia PA</p>
</div>
```

``` css
.event__title {
  lost-column: 1/1;
}

.event__date,
.event__location {
  lost-column: 1/2;
}
```

LostGrid will have a hard time with the grid within the `html`, though. I suppose it could be done but I'd have to ponder the best way to use the `margin-right: 0;` that the `cycle` manages.
