### ISSUE TITLE
does lost support rtl for grid system ?

### ISSUE THREAD

**Issue by hemedani** [peterramsing/lost#288]
in jeet we have an rtl option in configuration like this :

```
jeet = {
  gutter: 3,
  parent-first: false,
  layout-direction: RTL
}
```

for changing the floating statement  to right.
I'm searching a bit and not find any configuration option  specially for rtl (right to left). how can use lost with floating element to right?

**Comment by peterramsing** [comment]
Unless @corysimmons has a hidden feature somewhere for this, LostGrid doesn't support RTL.

Although maybe it should.

**Comment by corysimmons** [comment]
https://github.com/MohammadYounes/rtlcss

This way Lost doesn't need to maintain an extra tool.

**Comment by peterramsing** [comment]
@corysimmons ...and that's why you're so cool! Thanks for the tip!

**Comment by corysimmons** [comment]
No problem. Feel free to ping me anytime. =)

**Comment by hemedani** [comment]
Thanks for @corysimmons  and @peterramsing  for your favors ...
But if we just want's to use flexbox of lost we just need to care of the margin's right and left and the master direction statement for example:
it's the orginal code generate from `lost-column 1/3 3 15px` with flexbox:

``` css
.*** {
  -ms-flex: 0 0 auto;
      flex: 0 0 auto;
  width: calc(99.99% * 1/3 - (15px - 15px * 1/3));
}
.***:nth-child(1n) {
  margin-right: 15px;
  margin-left: 0;
}
.***:last-child {
  margin-right: 0;
}
.***:nth-child(3n) {
  margin-right: 0;
  margin-left: auto;
}
```

and if we want's to get the rtl version we just need to change the margin's like this :

``` css
body {
  direction: rtl;
}
.*** {
  -ms-flex: 0 0 auto;
      flex: 0 0 auto;
  width: calc(99.99% * 1/3 - (15px - 15px * 1/3));
}
.***:nth-child(1n) {
  margin-left: 15px;
  margin-right: 0;
}
.***:last-child {
  margin-left: 0;
}
.***:nth-child(3n) {
  margin-left: 0;
  margin-right: auto;
}
```

just that, It's very nice if we add this feature for flexbox in awesome gridsystem lost

**Comment by corysimmons** [comment]
Hmmm.... I'm not sure if Lost can fix this. If we set up this stuff for Lost, then people won't be able to use rtlcss together.

@MohammadYounes Do you happen to have any ideas for this?

**Comment by MohammadYounes** [comment]
@corysimmons As lost is usually embedded inside a larger CSS, Having this as an option would only benefit authors writing RTL only CSS. 

But for authors writing LTR CSS that needs to be converted to RTL at a later stage,such option would be useless.

**Comment by MohammadYounes** [comment]
Moreover, RTL authors can limit the scope of rtlcss to lost output only using [postcss-plugin-context](https://github.com/postcss/postcss-plugin-context):

``` js
var postcss = require('postcss');
var lost = require('lost');
var rtlcss = require('rtlcss');
var context = require('postcss-plugin-context');

var css = `
.will-remain-LTR {
  direction:ltr;
}
@context rtl {

  .will-be-RTL{
    direction:ltr;
  }

  @lost flexbox flex;
  .*** {
    lost-column: 1/3 3 15px; 
  }

}`;

postcss([lost, context({rtl:rtlcss})]).process(css).then(function (result) {
    result.warnings().forEach(function (warn) {
        console.warn(warn.toString());
    });
    console.log(result.css);
});
```

Will give you:

``` css
.will-remain-LTR { 
  direction:ltr;
}
.will-be-RTL{
  direction:rtl;
}
.*** {
  flex:0 0 auto;
  width:calc(99.99% * 1/3 - (15px - 15px * 1/3));
}
.***:nth-child(1n) {
  margin-left:15px;
  margin-right:0;
}
.***:last-child {
  margin-left:0;
}
.***:nth-child(3n) {
  margin-left:0;
  margin-right:auto;
}
```
