### ISSUE TITLE
odd behaviour of variables

### ISSUE THREAD

**Issue by cmnstmntmn** [peterramsing/lost#310]
i'm using lost with webpack

for this input

``` css
@lost gutter var(--gs-gutter);
@lost flexbox flex;

.container {
    lost-center: 980px var(--gs-padding);
}

.half {
    lost-column: 1/2;
}

```

i get the expected output for the **.container**

``` css
.container {
    display: flex;
    flex-flow: row wrap;
    max-width: 980px;
    margin-left: auto;
    margin-right: auto;
    padding-left: 1.5rem;
    padding-right: 1.5rem;
}
```

but not for the **.half**

``` css
.half:nth-child(2n) {
    margin-right: 0;
    margin-left: auto;
}
.half:last-child {
    margin-right: 0;
}
.half:nth-child(1n) {
    margin-right: var(--gs-gutter);
    margin-left: 0;
}
.half {
    flex: 0 0 auto;
    width: calc(99.99% * 1/2 - (var(--gs-gutter) - var(--gs-gutter) * 1/2));
}
```

variables aren't parsed

i'm using  `lost: "^6.8.1"` and variable values are in **rem**
