### ISSUE TITLE
lost-masonry-column does not support no unit on a "0 gutter"

### ISSUE THREAD

**Issue by peterramsing** [peterramsing/lost#383]
**Is this a feature request or a bug report?**
Bug Report

**What is the current behavior?**
`lost-masonry-column` does not support a unitless zero gutter

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**
```css
.div {
  lost-masonry-column: 60px; 
  lost-masonry-column-gutter: 0;
}
```
Error: `TypeError: Cannot read property 'join' of null`

**What is the desired behavior?**
Supporting unitless zero gutters.

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
8.0.0

**Anything else?**
Failing tests: https://travis-ci.org/peterramsing/lost/jobs/249156939
