### ISSUE TITLE
Incorrect lost-offset with -negative fraction in row

### ISSUE THREAD

**Issue by asifshirazi** [peterramsing/lost#394]
**Is this a feature request or a bug report?**
Bug

Hi,
The **lost-offset** documentation says:
> Margin to the left, right, bottom, or top, of an element depending on if the fraction passed is positive or negative. It works for both horizontal and vertical grids.

But as you can see below the`.append-row` ruleset result is not coming with margin-right.

#### Source
``` css
.prepend-col { lost-offset: 1/3 column; }
.append-col { lost-offset: -1/3 column; }

.prepend-row { lost-offset: 1/3; }
.append-row { lost-offset: -1/3; }
```

#### Result
``` css
.prepend-col { margin-bottom: calc(33.3% + 27px) !important; }
.append-col { margin-top: calc(33.3% + 7px) !important; }

.prepend-row { margin-left: calc(33.3% + 7px) !important; }
.append-row { margin-left: calc(-33.3% - 7px) !important; }
```
