### ISSUE TITLE
Media queries don't work with @lost variables

### ISSUE THREAD

**Issue by elliottmangham** [peterramsing/lost#407]
Hello,

Is it possible - _and if so how_ - to change @lost variables using media queries?

For example I have my gutter set to 30px:
`@lost gutter 30px;`

This works. However, I want to have my gutter set to `6vw` on mobile and the follow does **not** work:
```css
@lost gutter 30px;

@media screen and (max-width: 480px) {
	@lost gutter 7vw;
}
```

Please can you advise how to get this working?

Thank you.

**Comment by peterramsing** [comment]
@elliottmangham Simply put: this isn't something that LostGrid supports. LostGrid transpiles before it ever sees the browser so it doesn't adapt to media queries.

## Action Steps:
1. You can support this on an individual basis with the following:
```css
.foo {
  lost-column: 1/3 3 30px;
}
@media () {
  .foo {
    lost-column: 1/3 3 7vw;
  }
}
```
I suspect that isn't ideal for what you're intending here as that can get pretty tedious to write.

2. Build out support for if a global setting is set within a media query that LostGrid then duplicates each declaration with those different globals set. That has some possible downsides with CSS bloat. It could be pondered, though.

**Comment by elliottmangham** [comment]
Thanks @peterramsing for your informative answer, really helpful!

Your action step 1 is a good workaround, although I find that would generate a lot of unnecessary code as it would output the floats, margins, etc. for every media query.

Is it possible to modify only the gutter, for example:
```css
.foo {
  lost-column: 1/3 3 30px;
}
@media () {
  .foo {
    lost-gutter: 7vw;
  }
}
```

Thanks again
