### ISSUE TITLE
Multiple cycles within one container

### ISSUE THREAD

**Issue by JanisOzolins** [peterramsing/lost#434]
```
+------------------------------------------------+
|                   Container                    |
|+----------------------------------------------+|
||                      1                       ||
|+----------------------------------------------+|
|+---------------++--------------++-------------+|
||       2       ||       3      ||      4      ||
|+---------------++--------------++-------------+|
|+---------------++--------------++-------------+|
||       5       ||       6      ||     7       ||
|+---------------++--------------++-------------+|
|+----------------------------------------------+|
||                      8                       ||
|+----------------------------------------------+|
+------------------------------------------------+ 
```

I'm trying to create the following grid layout, however with the following code:

```
.one {
   lost-column: 1/1 1;
}

.two, .three, .four {
   lost-column: 1/3;
}

.five, .six, .seven {
   lost-column: 1/3;
}

.eight {
   lost-column: 1/1 1;
}
```

How can I use multiple cycles within the same container? For some reason it thinks that container one is part of the three (1/3) column row, making Container 3 the last element instead of Container 4.

Is it even possible to achieve this kind of layout with Lost Grid?

**Comment by peterramsing** [comment]
@JanisOzolins, sorry for the delay.

Yes, this type of layout is possible. The issue you're running into is the cycle is based on the "children". Here's the code that generates this and I'll comment inline:

```css
.one {
  lost-column: 1/1 1;
}

.two,
.three,
.four {
  lost-column: 1/3 4;
  /* 
    What the cycle does is "reset" the last child based on the cycle. Because "four" is the end of this
    row it should be the item with the reset. You can tell LostGrid about this by giving these three a
    cycle of 4.
  */
}

.five,
.six,
.seven {
  lost-column: 1/3 7;
  /* 
    Just like the last group, the last item in this row is the "seventh" in the group. Setting the cycle to 
    seven will then reset the seventh item instead of the sixth (if it were a 1/3 grid it'd reset the 3rd, 
    6th, etc).
  */
}

.eight {
  lost-column: 1/1 1;
}
```

![screen shot 2018-12-21 at 16 07 15](https://user-images.githubusercontent.com/3523268/50368177-b128e480-053a-11e9-9309-0536beeafa26.jpg)

Hopefully, that helps. Let me know if you have any additional questions.
